pki:
  ca: ca.crt
  cert: host.crt
  key: host.key

static_host_map:
  "10.250.31.2": ["my-lighthouse.example.com:4242", "45.55.66.77':4242"]

lighthouse:
  am_lighthouse: true
  interval: 60
  #hosts:
  #  - "10.250.31.2"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: false

relay:
  am_relay: false
  use_relays: false

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: any
      proto: tcp
      host: any
